<article class="sidebar">
    <h3>Menu</h3>
        <h4>バーガー</h4>
            <ul>
                <li>ハンバーガー</li>
                <li>チーズバーガー</li>
                <li>テリヤキバーガー</li>
                <li>アボガドバーガー</li>
                <li>フィッシュバーガー</li>
                <li>ベーコンバーガー</li>
                <li>チキンバーガー</li>
            </ul>
        <h4>サイド</h4>
            <ul>
                <li>ポテト</li>
                <li>サラダ</li>
                <li>ナゲット</li>
                <li>コーン</li>
            </ul>
        <h4>ドリンク</h4>
            <ul>
                <li>コーラ</li>
                <li>ファンタ</li>
                <li>オレンジ</li>
                <li>アップル</li>
                <li>紅茶（Ice/Hot）</li>
                <li>コーヒー（Ice/Hot）</li>
            </ul>
</article>